[package]
name = "wizARds"
version = "0.0.1"
edition = "2021"
description = "Example for building an Android OpenXR app with Bevy"

[lib]
name = "wizARds"
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "wizARds"
path = "src/main.rs"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "d4132f661a8a567fd3f9c3b329c2b4032bb1e05e" }
bevy_xpbd_3d = { git = "https://github.com/goudanough/bevy_xpbd", rev = "771276761479c2d5bd8f814e3f9164c39103f083" }
cpal = "0.15.2"
crossbeam = "0.8.4"
vosk = "0.2.0"
bevy_oxr = { git = "https://github.com/goudanough/bevy_oxr", rev = "d2a4b79b01b1dab4412015177026664ff1947121", default-features = false }

[target.'cfg(target_os = "android")'.dependencies]
# bevy_oxr = { git = "https://github.com/awtterpip/bevy_oxr", default-features = false }


[profile.release]
opt-level = 3
lto = "thin"

# I've added this because it could technically give a faster binary
[profile.super-release]
inherits = "release"
lto = "fat"
codegen-units = 1
panic = "abort"
