[package]
name = "wizARds"
version = "0.0.1"
edition = "2021"
description = "Example for building an Android OpenXR app with Bevy"

[lib]
name = "wizARds"
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "wizARds"
path = "src/main.rs"

[dependencies]
bevy = "0.12"
bevy_xpbd_3d = "0.3.3"
cpal = "0.15.2"
crossbeam = "0.8.4"
vosk = "0.2.0"

[target.'cfg(target_os = "android")'.dependencies]
# bevy_oxr = { git = "https://github.com/awtterpip/bevy_oxr", default-features = false }
bevy_oxr = { git = "https://github.com/goudanough/bevy_oxr", default-features = false, rev="386a53d" }

[profile.release]
opt-level = 3
lto = "thin"

# I've added this because it could technically give a faster binary
[profile.super-release]
inherits = "release"
lto = "fat"
codegen-units = 1
panic = "abort"
